// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGeneralParams creates a new GeneralParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGeneralParams() *GeneralParams {
	return &GeneralParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGeneralParamsWithTimeout creates a new GeneralParams object
// with the ability to set a timeout on a request.
func NewGeneralParamsWithTimeout(timeout time.Duration) *GeneralParams {
	return &GeneralParams{
		timeout: timeout,
	}
}

// NewGeneralParamsWithContext creates a new GeneralParams object
// with the ability to set a context for a request.
func NewGeneralParamsWithContext(ctx context.Context) *GeneralParams {
	return &GeneralParams{
		Context: ctx,
	}
}

// NewGeneralParamsWithHTTPClient creates a new GeneralParams object
// with the ability to set a custom HTTPClient for a request.
func NewGeneralParamsWithHTTPClient(client *http.Client) *GeneralParams {
	return &GeneralParams{
		HTTPClient: client,
	}
}

/* GeneralParams contains all the parameters to send to the API endpoint
   for the general operation.

   Typically these are written to a http.Request.
*/
type GeneralParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the general params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GeneralParams) WithDefaults() *GeneralParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the general params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GeneralParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the general params
func (o *GeneralParams) WithTimeout(timeout time.Duration) *GeneralParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the general params
func (o *GeneralParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the general params
func (o *GeneralParams) WithContext(ctx context.Context) *GeneralParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the general params
func (o *GeneralParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the general params
func (o *GeneralParams) WithHTTPClient(client *http.Client) *GeneralParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the general params
func (o *GeneralParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GeneralParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
