// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsDeleteUserReq models delete user req
//
// swagger:model models.DeleteUserReq
type ModelsDeleteUserReq struct {

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this models delete user req
func (m *ModelsDeleteUserReq) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models delete user req based on context it is used
func (m *ModelsDeleteUserReq) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsDeleteUserReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsDeleteUserReq) UnmarshalBinary(b []byte) error {
	var res ModelsDeleteUserReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
