// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsCreateUserReq models create user req
//
// swagger:model models.CreateUserReq
type ModelsCreateUserReq struct {

	// address
	Address string `json:"address,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this models create user req
func (m *ModelsCreateUserReq) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models create user req based on context it is used
func (m *ModelsCreateUserReq) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsCreateUserReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsCreateUserReq) UnmarshalBinary(b []byte) error {
	var res ModelsCreateUserReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
